services:
  app:
    image: todo
    build: .
    container_name: app
    ports:
      - "5000:80"
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:80 wsgi:app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - web

  db:
    container_name: db
    image: mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./.data:/var/lib/mysql
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  .data:
    driver:
      pymysql
