services:
  app:
    image: todo
    build: .
    container_name: app
    ports:
      - "5000:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
        db:
          condition: service_healthy
    networks:
      - web

  db:
    container_name: db
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--password=$${DATABASE_PASSWORD}"]
      start_period: 2m
      start_interval: 5s
    env_file:
      - .env
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - ./.data:/var/lib/mysql
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  .data:
    driver:
      pymysql
